name: BukkitCLI
main: de.wrenchbox.cli.BukkitCLI
author: AmShaegar
version: 1.0
description: BukkitCLI provides a simple way for plugins to execute commands on the command line and can be used as API.
